### ISSUE TITLE
Implement generic functions to calculate AOO and EOO from different objects

### ISSUE THREAD

**Issue by jrfep** [red-list-ecosystem/redlistr#13]
I think the most elegant solution would be to implement a generic function:
```
makeAOO <- function (object, ...)
UseMethod("makeAOO")
```
And then have methods to handle different spatial objects. 

Need to explore some background/tutorials for this:
- https://rstudio.github.io/r-manuals/r-intro/Writing-your-own-functions.html#classes-generic-functions-and-object-orientation
- https://www.stat.umn.edu/geyer/3701/notes/generic.html

**Comment by calvinkflee** [comment]
@jrfep I agree that's probably the best way forward, and can help clean up some of the other code as well. Right now I just have a very simple (and messy) If statement at the beginning of some of the functions that it runs through, and an error that can't be interpreted properly if the input format isn't included in that list.

Are you working on this? Otherwise I think I might be able to get something up and tested relatively quickly!

**Comment by jrfep** [comment]
Hi @calvinkflee,
Thanks, that is great! 
I was thinking about this, but haven't got time to actually implement it. Will try to find some time to review the code.
